create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    message text,
    type text not null default 'system',
    read_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
on public.notifications(user_id, created_at desc);

create index if not exists notifications_unread_idx
on public.notifications(user_id, read_at)
where read_at is null;

alter table public.notifications enable row level security;

drop policy if exists notifications_self_select on public.notifications;
create policy notifications_self_select
on public.notifications
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists notifications_self_update on public.notifications;
create policy notifications_self_update
on public.notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.admin_send_notification(
    p_user_id uuid,
    p_title text,
    p_message text,
    p_type text default 'announcement'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    new_id bigint;
begin
    if not public.is_admin() then
        raise exception 'Admin access required';
    end if;

    insert into public.notifications(user_id,title,message,type)
    values(p_user_id,p_title,p_message,coalesce(p_type,'announcement'))
    returning id into new_id;

    return new_id;
end;
$$;

grant execute on function public.admin_send_notification(uuid,text,text,text)
to authenticated;

create or replace function public.admin_broadcast_notification(
    p_title text,
    p_message text,
    p_type text default 'announcement'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count bigint;
begin
    if not public.is_admin() then
        raise exception 'Admin access required';
    end if;

    insert into public.notifications(user_id,title,message,type)
    select id,p_title,p_message,coalesce(p_type,'announcement')
    from auth.users
    where id is not null;

    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

grant execute on function public.admin_broadcast_notification(text,text,text)
to authenticated;

create or replace function public.admin_gift_coins(
    p_user_id uuid,
    p_amount integer,
    p_reason text default 'Coins gifted by admin'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    new_balance integer;
begin
    if not public.is_admin() then
        raise exception 'Admin access required';
    end if;

    if p_amount <= 0 then
        raise exception 'Coin amount must be greater than zero';
    end if;

    update public.profiles
    set coins = coalesce(coins,0) + p_amount,
        updated_at = now()
    where id = p_user_id
    returning coins into new_balance;

    if new_balance is null then
        raise exception 'User profile not found';
    end if;

    insert into public.coin_transactions(
        user_id,
        amount,
        balance_after,
        type,
        description
    )
    values(
        p_user_id,
        p_amount,
        new_balance,
        'admin_gift',
        coalesce(p_reason,'Coins gifted by admin')
    );

    insert into public.notifications(
        user_id,
        title,
        message,
        type
    )
    values(
        p_user_id,
        'Coins gifted',
        'You received ' || p_amount::text || ' coins from DECAN MOVIE. Your new balance is ' || new_balance::text || ' coins.',
        'coin_gift'
    );

    return new_balance;
end;
$$;

grant execute on function public.admin_gift_coins(uuid,integer,text)
to authenticated;

create or replace function public.get_my_coin_balance()
returns integer
language sql
security definer
set search_path = public
as $$
    select coalesce(coins,0)
    from public.profiles
    where id = auth.uid();
$$;

grant execute on function public.get_my_coin_balance()
to authenticated;

create or replace function public.mark_all_notifications_read()
returns bigint
language sql
security definer
set search_path = public
as $$
    with updated as (
        update public.notifications
        set read_at = now()
        where user_id = auth.uid()
          and read_at is null
        returning id
    )
    select count(*) from updated;
$$;

grant execute on function public.mark_all_notifications_read()
to authenticated;

create or replace function public.admin_post_to_users(
    p_title text,
    p_message text,
    p_type text default 'announcement'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
    return public.admin_broadcast_notification(
        p_title,
        p_message,
        p_type
    );
end;
$$;

grant execute on function public.admin_post_to_users(text,text,text)
to authenticated;
