
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  coins integer not null default 0 check (coins >= 0),
  xp integer not null default 0 check (xp >= 0),
  streak_days integer not null default 0 check (streak_days >= 0),
  status text not null default 'active' check (status in ('active','suspended')),
  last_reward_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.movie_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_id bigint not null,
  media_type text not null default 'movie' check (media_type in ('movie','tv')),
  rating numeric(2,1) not null check (rating >= 1 and rating <= 5),
  title text,
  poster_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, movie_id, media_type)
);

create table if not exists public.watch_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  movie_id bigint not null,
  media_type text not null default 'movie' check (media_type in ('movie','tv')),
  title text,
  poster_path text,
  event_type text not null check (event_type in ('detail','play','complete','progress','watchlist_add','favorite_add','search')),
  season integer,
  episode integer,
  progress_seconds integer,
  duration_seconds integer,
  created_at timestamptz not null default now()
);

create index if not exists watch_events_created_idx on public.watch_events(created_at desc);
create index if not exists watch_events_movie_idx on public.watch_events(movie_id, media_type, created_at desc);

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  path text,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists site_visits_created_idx on public.site_visits(created_at desc);

create table if not exists public.coin_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  balance_after integer,
  type text not null,
  description text,
  reference_id text,
  created_at timestamptz not null default now()
);
create index if not exists coin_transactions_user_idx on public.coin_transactions(user_id, created_at desc);

create table if not exists public.daily_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  claim_date date not null default current_date,
  amount integer not null,
  created_at timestamptz not null default now(),
  unique(user_id, claim_date)
);

create table if not exists public.movie_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  requester_name text,
  title text not null,
  year integer,
  media_type text default 'movie' check (media_type in ('movie','tv','anime','other')),
  message text,
  status text not null default 'pending' check (status in ('pending','reviewing','approved','rejected','completed')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists movie_requests_status_idx on public.movie_requests(status, created_at desc);


create table if not exists public.user_library (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  library_type text not null check (library_type in ('watchlist','favorites','history','customlist','continue')),
  movie_id bigint not null,
  media_type text,
  item jsonb not null,
  updated_at timestamptz not null default now(),
  unique(user_id, library_type, movie_id)
);
create index if not exists user_library_user_type_idx on public.user_library(user_id, library_type);

alter table public.user_library enable row level security;
drop policy if exists user_library_self on public.user_library;
create policy user_library_self on public.user_library for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid());

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text,
  type text default 'system',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    nullif(split_part(coalesce(new.email,''),'@',1),''),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(coalesce(new.email,''),'@',1))
  )
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.movie_ratings enable row level security;
alter table public.watch_events enable row level security;
alter table public.site_visits enable row level security;
alter table public.coin_transactions enable row level security;
alter table public.daily_claims enable row level security;
alter table public.movie_requests enable row level security;
alter table public.notifications enable row level security;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists roles_self_select on public.user_roles;
create policy roles_self_select on public.user_roles for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists ratings_self_select on public.movie_ratings;
create policy ratings_self_select on public.movie_ratings for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists ratings_self_insert on public.movie_ratings;
create policy ratings_self_insert on public.movie_ratings for insert with check (user_id = auth.uid());
drop policy if exists ratings_self_update on public.movie_ratings;
create policy ratings_self_update on public.movie_ratings for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists ratings_self_delete on public.movie_ratings;
create policy ratings_self_delete on public.movie_ratings for delete using (user_id = auth.uid() or public.is_admin());

drop policy if exists watch_events_insert on public.watch_events;
create policy watch_events_insert on public.watch_events for insert with check (user_id = auth.uid() or user_id is null);
drop policy if exists watch_events_self_select on public.watch_events;
create policy watch_events_self_select on public.watch_events for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists visits_insert on public.site_visits;
create policy visits_insert on public.site_visits for insert with check (user_id = auth.uid() or user_id is null);
drop policy if exists visits_admin_select on public.site_visits;
create policy visits_admin_select on public.site_visits for select using (public.is_admin());

drop policy if exists coin_self_select on public.coin_transactions;
create policy coin_self_select on public.coin_transactions for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists claims_self_select on public.daily_claims;
create policy claims_self_select on public.daily_claims for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists requests_insert on public.movie_requests;
create policy requests_insert on public.movie_requests for insert with check (user_id = auth.uid() or user_id is null);
drop policy if exists requests_self_select on public.movie_requests;
create policy requests_self_select on public.movie_requests for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists requests_admin_update on public.movie_requests;
create policy requests_admin_update on public.movie_requests for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists notifications_self_select on public.notifications;
create policy notifications_self_select on public.notifications for select using (user_id = auth.uid());
drop policy if exists notifications_self_update on public.notifications;
create policy notifications_self_update on public.notifications for update using (user_id = auth.uid());

create or replace view public.top_watched_today as
select movie_id, media_type, max(title) as title, max(poster_path) as poster_path,
       count(*) filter (where event_type in ('play','complete')) as watches,
       count(distinct coalesce(user_id::text, session_id)) as unique_viewers
from public.watch_events
where created_at >= current_date
group by movie_id, media_type
order by watches desc;

create or replace view public.rating_summary as
select count(*)::bigint as total_ratings,
       round(avg(rating)::numeric,2) as average_rating,
       count(distinct user_id)::bigint as rating_users
from public.movie_ratings;

create or replace function public.claim_daily_reward()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  today date := current_date;
  existing_id bigint;
  reward integer := 10;
  new_balance integer;
  streak integer := 1;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  select id into existing_id from public.daily_claims
  where user_id = uid and claim_date = today;

  if existing_id is not null then
    select coins, streak_days into new_balance, streak from public.profiles where id = uid;
    return jsonb_build_object('claimed', false, 'amount', 0, 'coins', coalesce(new_balance,0), 'streak', coalesce(streak,0));
  end if;

  select coalesce(streak_days,0), coalesce(coins,0)
    into streak, new_balance
  from public.profiles where id = uid for update;

  if not exists (
    select 1 from public.daily_claims
    where user_id = uid and claim_date = today - 1
  ) then
    streak := 1;
  else
    streak := greatest(1, streak + 1);
  end if;

  reward := 10 + least(streak, 7) * 2;
  new_balance := new_balance + reward;

  update public.profiles
  set coins = new_balance, streak_days = streak, last_reward_date = today, updated_at = now()
  where id = uid;

  insert into public.daily_claims(user_id, claim_date, amount) values(uid, today, reward);
  insert into public.coin_transactions(user_id, amount, balance_after, type, description)
  values(uid, reward, new_balance, 'daily_reward', 'Daily login reward');

  return jsonb_build_object('claimed', true, 'amount', reward, 'coins', new_balance, 'streak', streak);
end;
$$;

grant execute on function public.claim_daily_reward() to authenticated;

create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select jsonb_build_object(
    'total_users', (select count(*) from auth.users),
    'users_today', (select count(*) from auth.users where created_at >= current_date),
    'visitors_today', (select count(distinct coalesce(user_id::text, session_id)) from site_visits where created_at >= current_date),
    'visits_today', (select count(*) from site_visits where created_at >= current_date),
    'ratings', (select count(*) from movie_ratings),
    'rating_users', (select count(distinct user_id) from movie_ratings),
    'coins', (select coalesce(sum(coins),0) from profiles),
    'watch_events_today', (select count(*) from watch_events where created_at >= current_date),
    'pending_requests', (select count(*) from movie_requests where status='pending'),
    'total_requests', (select count(*) from movie_requests)
  ) into result;
  return result;
end;
$$;
grant execute on function public.admin_dashboard_stats() to authenticated;

drop function if exists public.admin_users(integer);

create or replace function public.admin_users(limit_count integer default 100)
returns table(
  id uuid, email text, username text, display_name text, coins integer, xp integer,
  streak_days integer, status text, created_at timestamptz, role text
)
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  return query
  select p.id, u.email, p.username, p.display_name, p.coins, p.xp,
         p.streak_days, p.status, p.created_at, coalesce(r.role,'user')
  from public.profiles p
  join auth.users u on u.id=p.id
  left join public.user_roles r on r.user_id=p.id
  order by p.created_at desc
  limit greatest(1, least(limit_count,500));
end;
$$;
grant execute on function public.admin_users(integer) to authenticated;

create or replace function public.admin_adjust_coins(target_user uuid, amount integer, reason text default 'Admin adjustment')
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare new_balance integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  update public.profiles set coins=greatest(0,coins+amount), updated_at=now()
  where id=target_user returning coins into new_balance;
  if new_balance is null then raise exception 'User not found'; end if;
  insert into public.coin_transactions(user_id,amount,balance_after,type,description)
  values(target_user,amount,new_balance,'admin_adjustment',reason);
  return jsonb_build_object('coins',new_balance);
end;
$$;
grant execute on function public.admin_adjust_coins(uuid,integer,text) to authenticated;

create or replace function public.admin_set_user_status(target_user uuid, new_status text)
returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if new_status not in ('active','suspended') then raise exception 'Invalid status'; end if;
  update public.profiles set status=new_status, updated_at=now() where id=target_user;
  return found;
end;
$$;
grant execute on function public.admin_set_user_status(uuid,text) to authenticated;

create or replace function public.top_watched_public(limit_count integer default 24)
returns table(movie_id bigint, media_type text, title text, poster_path text, watches bigint, unique_viewers bigint)
language sql stable
security definer set search_path = public
as $$
  select movie_id, media_type, max(title), max(poster_path),
         count(*) filter (where event_type in ('play','complete')),
         count(distinct coalesce(user_id::text, session_id))
  from public.watch_events
  where created_at >= current_date
  group by movie_id, media_type
  order by 5 desc
  limit greatest(1, least(limit_count,50));
$$;
grant execute on function public.top_watched_public(integer) to anon, authenticated;

create table if not exists public.movie_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  movie_id bigint not null,
  media_type text not null check (media_type in ('movie','tv')),
  body text not null check (char_length(trim(body)) between 1 and 4000),
  spoiler boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_likes (
  review_id uuid not null references public.movie_reviews(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(review_id,user_id)
);

create table if not exists public.user_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(follower_id,following_id),
  check(follower_id <> following_id)
);

create table if not exists public.achievements (
  id text primary key,
  name text not null,
  description text not null,
  xp integer not null default 0
);

create table if not exists public.user_achievements (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_id text not null references public.achievements(id) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key(user_id,achievement_id)
);

alter table public.movie_reviews enable row level security;
alter table public.review_likes enable row level security;
alter table public.user_follows enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;

drop policy if exists "reviews public read" on public.movie_reviews;
create policy "reviews public read" on public.movie_reviews for select using (true);
drop policy if exists "reviews own insert" on public.movie_reviews;
create policy "reviews own insert" on public.movie_reviews for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "reviews own update" on public.movie_reviews;
create policy "reviews own update" on public.movie_reviews for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "reviews own delete" on public.movie_reviews;
create policy "reviews own delete" on public.movie_reviews for delete to authenticated using (auth.uid()=user_id);

drop policy if exists "review likes public read" on public.review_likes;
create policy "review likes public read" on public.review_likes for select using (true);
drop policy if exists "review likes own" on public.review_likes;
create policy "review likes own" on public.review_likes for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "follows public read" on public.user_follows;
create policy "follows public read" on public.user_follows for select using (true);
drop policy if exists "follows own" on public.user_follows;
create policy "follows own" on public.user_follows for all to authenticated using (auth.uid()=follower_id) with check (auth.uid()=follower_id);

drop policy if exists "achievements public read" on public.achievements;
create policy "achievements public read" on public.achievements for select using (true);
drop policy if exists "user achievements public read" on public.user_achievements;
create policy "user achievements public read" on public.user_achievements for select using (true);

insert into public.achievements(id,name,description,xp) values
('first_review','First Review','Publish your first movie review.',25),
('five_movies','Movie Explorer','Rate or watch five titles.',50),
('ten_day_streak','10 Day Streak','Maintain a ten-day activity streak.',100)
on conflict (id) do nothing;

create index if not exists movie_reviews_movie_idx on public.movie_reviews(movie_id,media_type,created_at desc);
create index if not exists review_likes_review_idx on public.review_likes(review_id);
create index if not exists follows_following_idx on public.user_follows(following_id);

create extension if not exists pgcrypto;

create table if not exists public.movie_views (
  id bigint generated by default as identity primary key,
  tmdb_id bigint not null,
  media_type text not null check (media_type in ('movie','tv')),
  title text,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  season_number integer,
  episode_number integer,
  viewed_at timestamptz not null default now()
);

create index if not exists movie_views_tmdb_idx on public.movie_views(tmdb_id,media_type,viewed_at desc);


alter table public.user_roles add column if not exists permissions jsonb not null default '{}'::jsonb;

do $$
begin
  alter table public.user_roles drop constraint if exists user_roles_role_check;
  alter table public.user_roles add constraint user_roles_role_check check (role in ('user','admin','super_admin'));
exception when duplicate_object then null;
end $$;

alter table public.profiles add column if not exists verification_status text not null default 'unverified';
alter table public.profiles add column if not exists location text;
alter table public.profiles add column if not exists favorite_genre text;
alter table public.profiles add column if not exists bio text;

do $$
begin
  alter table public.profiles drop constraint if exists profiles_verification_status_check;
  alter table public.profiles add constraint profiles_verification_status_check check (verification_status in ('unverified','pending','verified','rejected'));
exception when duplicate_object then null;
end $$;

create table if not exists public.support_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  reporter_email text,
  reporter_name text,
  category text not null default 'bug',
  subject text not null,
  message text not null,
  page_url text,
  status text not null default 'open',
  priority text not null default 'normal',
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  alter table public.support_reports drop constraint if exists support_reports_category_check;
  alter table public.support_reports add constraint support_reports_category_check check (category in ('bug','account','content','payment','security','other'));
  alter table public.support_reports drop constraint if exists support_reports_status_check;
  alter table public.support_reports add constraint support_reports_status_check check (status in ('open','in_progress','resolved','closed'));
  alter table public.support_reports drop constraint if exists support_reports_priority_check;
  alter table public.support_reports add constraint support_reports_priority_check check (priority in ('low','normal','high','urgent'));
exception when duplicate_object then null;
end $$;

create index if not exists support_reports_status_idx on public.support_reports(status, created_at desc);
create index if not exists support_reports_user_idx on public.support_reports(user_id, created_at desc);

alter table public.support_reports enable row level security;

drop policy if exists support_reports_insert on public.support_reports;
create policy support_reports_insert on public.support_reports for insert with check (user_id = auth.uid() or user_id is null);

drop policy if exists support_reports_self_select on public.support_reports;
create policy support_reports_self_select on public.support_reports for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists support_reports_admin_update on public.support_reports;
create policy support_reports_admin_update on public.support_reports for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists notifications_admin_insert on public.notifications;
create policy notifications_admin_insert on public.notifications for insert with check (public.is_admin());

drop policy if exists notifications_admin_update on public.notifications;
create policy notifications_admin_update on public.notifications for update using (public.is_admin()) with check (public.is_admin());

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.user_roles
    where user_id = auth.uid()
      and role in ('admin','super_admin')
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.claim_daily_reward()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  today date := current_date;
  reward integer;
  new_balance integer;
  streak integer;
  inserted_id bigint;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  insert into public.profiles(id, display_name)
  select uid, coalesce(raw_user_meta_data->>'display_name', split_part(coalesce(email,''),'@',1))
  from auth.users
  where id = uid
  on conflict (id) do nothing;

  select coins, streak_days
  into new_balance, streak
  from public.profiles
  where id = uid
  for update;

  if exists(select 1 from public.daily_claims where user_id=uid and claim_date=today) then
    return jsonb_build_object(
      'claimed',false,
      'amount',0,
      'coins',coalesce(new_balance,0),
      'streak',coalesce(streak,0)
    );
  end if;

  if exists(select 1 from public.daily_claims where user_id=uid and claim_date=today-1) then
    streak := greatest(coalesce(streak,0)+1,1);
  else
    streak := 1;
  end if;

  reward := 10 + least(streak,7) * 2;
  new_balance := coalesce(new_balance,0) + reward;

  update public.profiles
  set coins=new_balance,
      streak_days=streak,
      last_reward_date=today,
      updated_at=now()
  where id=uid;

  insert into public.daily_claims(user_id,claim_date,amount)
  values(uid,today,reward)
  returning id into inserted_id;

  insert into public.coin_transactions(
    user_id,amount,balance_after,type,description,reference_id
  )
  values(
    uid,reward,new_balance,'daily_reward',
    'Daily login reward',inserted_id::text
  );

  return jsonb_build_object(
    'claimed',true,
    'amount',reward,
    'coins',new_balance,
    'streak',streak,
    'transaction_id',inserted_id
  );
end;
$$;

grant execute on function public.claim_daily_reward() to authenticated;

create or replace function public.record_real_view(
  p_tmdb_id bigint,
  p_media_type text,
  p_title text default null,
  p_session_id text default null,
  p_season_number integer default null,
  p_episode_number integer default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  total_views bigint;
begin
  if p_tmdb_id is null or p_tmdb_id <= 0 then
    raise exception 'Invalid TMDB ID';
  end if;

  if p_media_type not in ('movie','tv') then
    raise exception 'Invalid media type';
  end if;

  insert into public.movie_views(
    tmdb_id,media_type,title,user_id,session_id,season_number,episode_number
  )
  values(
    p_tmdb_id,p_media_type,p_title,uid,p_session_id,p_season_number,p_episode_number
  );

  insert into public.watch_events(
    user_id,session_id,movie_id,media_type,title,event_type,
    season,episode,created_at
  )
  values(
    uid,p_session_id,p_tmdb_id,p_media_type,p_title,'play',
    p_season_number,p_episode_number,now()
  );

  select count(*) into total_views
  from public.movie_views
  where tmdb_id=p_tmdb_id and media_type=p_media_type;

  return total_views;
end;
$$;

grant execute on function public.record_real_view(bigint,text,text,text,integer,integer) to anon, authenticated;

create or replace function public.get_real_movie_views(
  p_tmdb_id bigint,
  p_media_type text
)
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)
  from public.movie_views
  where tmdb_id=p_tmdb_id and media_type=p_media_type;
$$;

grant execute on function public.get_real_movie_views(bigint,text) to anon, authenticated;

create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  select jsonb_build_object(
    'total_users',(select count(*) from auth.users),
    'users_today',(select count(*) from auth.users where created_at >= current_date),
    'visitors_today',(select count(distinct coalesce(user_id::text,session_id)) from public.site_visits where created_at >= current_date),
    'visits_today',(select count(*) from public.site_visits where created_at >= current_date),
    'ratings',(select count(*) from public.movie_ratings),
    'rating_users',(select count(distinct user_id) from public.movie_ratings),
    'coins',(select coalesce(sum(coins),0) from public.profiles),
    'watch_events_today',(select count(*) from public.watch_events where event_type='play' and created_at >= current_date),
    'real_views_today',(select count(*) from public.movie_views where viewed_at >= current_date),
    'pending_requests',(select count(*) from public.movie_requests where status='pending'),
    'open_reports',(select count(*) from public.support_reports where status in ('open','in_progress')),
    'notifications',(select count(*) from public.notifications)
  ) into result;

  return result;
end;
$$;

grant execute on function public.admin_dashboard_stats() to authenticated;

create or replace function public.admin_users(limit_count integer default 100)
returns table(
  id uuid,
  email text,
  username text,
  display_name text,
  coins integer,
  xp integer,
  streak_days integer,
  status text,
  verification_status text,
  created_at timestamptz,
  role text,
  permissions jsonb
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  return query
  select
    p.id,
    u.email,
    p.username,
    p.display_name,
    p.coins,
    p.xp,
    p.streak_days,
    p.status,
    p.verification_status,
    p.created_at,
    coalesce(r.role,'user'),
    coalesce(r.permissions,'{}'::jsonb)
  from public.profiles p
  join auth.users u on u.id=p.id
  left join public.user_roles r on r.user_id=p.id
  order by p.created_at desc
  limit greatest(1,least(limit_count,500));
end;
$$;

grant execute on function public.admin_users(integer) to authenticated;

create or replace function public.admin_adjust_coins(
  target_user uuid,
  amount integer,
  reason text default 'Admin adjustment'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_balance integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  update public.profiles
  set coins=greatest(0,coalesce(coins,0)+amount),
      updated_at=now()
  where id=target_user
  returning coins into new_balance;

  if new_balance is null then raise exception 'User not found'; end if;

  insert into public.coin_transactions(
    user_id,amount,balance_after,type,description
  )
  values(
    target_user,amount,new_balance,'admin_adjustment',coalesce(reason,'Admin adjustment')
  );

  return jsonb_build_object('coins',new_balance);
end;
$$;

grant execute on function public.admin_adjust_coins(uuid,integer,text) to authenticated;

create or replace function public.admin_set_user_status(
  target_user uuid,
  new_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if new_status not in ('active','suspended') then raise exception 'Invalid status'; end if;

  update public.profiles
  set status=new_status,updated_at=now()
  where id=target_user;

  return found;
end;
$$;

grant execute on function public.admin_set_user_status(uuid,text) to authenticated;

create or replace function public.admin_set_role(
  target_user uuid,
  new_role text,
  new_permissions jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if new_role not in ('user','admin','super_admin') then raise exception 'Invalid role'; end if;

  insert into public.user_roles(user_id,role,permissions)
  values(target_user,new_role,coalesce(new_permissions,'{}'::jsonb))
  on conflict(user_id) do update
  set role=excluded.role,permissions=excluded.permissions;

  return true;
end;
$$;

grant execute on function public.admin_set_role(uuid,text,jsonb) to authenticated;

create or replace function public.admin_set_verification(
  target_user uuid,
  new_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if new_status not in ('unverified','pending','verified','rejected') then raise exception 'Invalid verification status'; end if;

  update public.profiles
  set verification_status=new_status,updated_at=now()
  where id=target_user;

  return found;
end;
$$;

grant execute on function public.admin_set_verification(uuid,text) to authenticated;

create or replace function public.admin_send_notification(
  target_user uuid,
  notification_title text,
  notification_message text,
  notification_type text default 'admin'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare notification_id bigint;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  insert into public.notifications(user_id,title,message,type)
  values(target_user,notification_title,notification_message,notification_type)
  returning id into notification_id;

  return notification_id;
end;
$$;

grant execute on function public.admin_send_notification(uuid,text,text,text) to authenticated;

create or replace function public.admin_broadcast_notification(
  notification_title text,
  notification_message text,
  notification_type text default 'announcement'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare sent_count bigint;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  insert into public.notifications(user_id,title,message,type)
  select id,notification_title,notification_message,notification_type
  from auth.users
  where not exists(
    select 1 from public.profiles p
    where p.id=auth.users.id and p.status='suspended'
  );

  get diagnostics sent_count = row_count;
  return sent_count;
end;
$$;

grant execute on function public.admin_broadcast_notification(text,text,text) to authenticated;

create or replace function public.admin_update_report(
  report_id bigint,
  new_status text,
  new_priority text default null,
  new_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  update public.support_reports
  set status=coalesce(new_status,status),
      priority=coalesce(new_priority,priority),
      admin_note=coalesce(new_note,admin_note),
      updated_at=now()
  where id=report_id;

  return found;
end;
$$;

grant execute on function public.admin_update_report(bigint,text,text,text) to authenticated;

create or replace function public.top_watched_public(limit_count integer default 24)
returns table(
  movie_id bigint,
  media_type text,
  title text,
  poster_path text,
  watches bigint,
  unique_viewers bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    movie_id,
    media_type,
    max(title),
    max(poster_path),
    count(*) filter(where event_type='play'),
    count(distinct coalesce(user_id::text,session_id))
  from public.watch_events
  where created_at >= current_date
  group by movie_id,media_type
  order by 5 desc
  limit greatest(1,least(limit_count,50));
$$;

grant execute on function public.top_watched_public(integer) to anon, authenticated;

create or replace view public.movie_view_totals as
select
  tmdb_id,
  media_type,
  max(title) as title,
  count(*) as views,
  max(viewed_at) as last_viewed_at
from public.movie_views
group by tmdb_id,media_type;

drop policy if exists reports_insert on public.support_reports;
create policy reports_insert on public.support_reports for insert with check (user_id=auth.uid() or user_id is null);

insert into public.user_roles(user_id,role,permissions)
select id,'super_admin',
'{"users":true,"verification":true,"roles":true,"movies":true,"trending":true,"news":true,"blogs":true,"notifications":true,"coins":true,"coin_gifts":true,"analytics":true,"settings":true,"admin_logs":true,"requests":true,"content":true,"support":true}'::jsonb
from auth.users
where id='f41e88f9-9abd-431e-be16-99ab0a671d2b'
on conflict(user_id) do update
set role='super_admin',
    permissions=excluded.permissions;

alter table public.movie_views enable row level security;

drop policy if exists movie_views_admin_select on public.movie_views;
create policy movie_views_admin_select on public.movie_views for select using (public.is_admin());

drop policy if exists movie_views_self_select on public.movie_views;
create policy movie_views_self_select on public.movie_views for select using (user_id=auth.uid());

grant select on public.movie_views to authenticated;
