-- DECAN MOVIE / SUPABASE UPGRADE
-- Optional accounts: guests can continue using the existing localStorage features.
-- Run this script in Supabase SQL Editor, then set your project URL + anon key in supabase-config.js.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  coins integer not null default 0 check (coins >= 0),
  xp integer not null default 0 check (xp >= 0),
  streak_days integer not null default 0 check (streak_days >= 0),
  status text not null default 'active' check (status in ('active','suspended')),
  last_reward_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.movie_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_id bigint not null,
  media_type text not null default 'movie' check (media_type in ('movie','tv')),
  rating numeric(2,1) not null check (rating >= 1 and rating <= 5),
  title text,
  poster_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, movie_id, media_type)
);

create table if not exists public.watch_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  movie_id bigint not null,
  media_type text not null default 'movie' check (media_type in ('movie','tv')),
  title text,
  poster_path text,
  event_type text not null check (event_type in ('detail','play','complete','progress','watchlist_add','favorite_add','search')),
  season integer,
  episode integer,
  progress_seconds integer,
  duration_seconds integer,
  created_at timestamptz not null default now()
);

create index if not exists watch_events_created_idx on public.watch_events(created_at desc);
create index if not exists watch_events_movie_idx on public.watch_events(movie_id, media_type, created_at desc);

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  path text,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists site_visits_created_idx on public.site_visits(created_at desc);

create table if not exists public.coin_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  balance_after integer,
  type text not null,
  description text,
  reference_id text,
  created_at timestamptz not null default now()
);
create index if not exists coin_transactions_user_idx on public.coin_transactions(user_id, created_at desc);

create table if not exists public.daily_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  claim_date date not null default current_date,
  amount integer not null,
  created_at timestamptz not null default now(),
  unique(user_id, claim_date)
);

create table if not exists public.movie_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id text,
  requester_name text,
  title text not null,
  year integer,
  media_type text default 'movie' check (media_type in ('movie','tv','anime','other')),
  message text,
  status text not null default 'pending' check (status in ('pending','reviewing','approved','rejected','completed')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists movie_requests_status_idx on public.movie_requests(status, created_at desc);


create table if not exists public.user_library (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  library_type text not null check (library_type in ('watchlist','favorites','history','customlist','continue')),
  movie_id bigint not null,
  media_type text,
  item jsonb not null,
  updated_at timestamptz not null default now(),
  unique(user_id, library_type, movie_id)
);
create index if not exists user_library_user_type_idx on public.user_library(user_id, library_type);

alter table public.user_library enable row level security;
drop policy if exists user_library_self on public.user_library;
create policy user_library_self on public.user_library for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid());

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text,
  type text default 'system',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    nullif(split_part(coalesce(new.email,''),'@',1),''),
    coalesce(new.raw_user_meta_data->>'display_name', split_part(coalesce(new.email,''),'@',1))
  )
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.movie_ratings enable row level security;
alter table public.watch_events enable row level security;
alter table public.site_visits enable row level security;
alter table public.coin_transactions enable row level security;
alter table public.daily_claims enable row level security;
alter table public.movie_requests enable row level security;
alter table public.notifications enable row level security;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists roles_self_select on public.user_roles;
create policy roles_self_select on public.user_roles for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists ratings_self_select on public.movie_ratings;
create policy ratings_self_select on public.movie_ratings for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists ratings_self_insert on public.movie_ratings;
create policy ratings_self_insert on public.movie_ratings for insert with check (user_id = auth.uid());
drop policy if exists ratings_self_update on public.movie_ratings;
create policy ratings_self_update on public.movie_ratings for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists ratings_self_delete on public.movie_ratings;
create policy ratings_self_delete on public.movie_ratings for delete using (user_id = auth.uid() or public.is_admin());

drop policy if exists watch_events_insert on public.watch_events;
create policy watch_events_insert on public.watch_events for insert with check (user_id = auth.uid() or user_id is null);
drop policy if exists watch_events_self_select on public.watch_events;
create policy watch_events_self_select on public.watch_events for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists visits_insert on public.site_visits;
create policy visits_insert on public.site_visits for insert with check (user_id = auth.uid() or user_id is null);
drop policy if exists visits_admin_select on public.site_visits;
create policy visits_admin_select on public.site_visits for select using (public.is_admin());

drop policy if exists coin_self_select on public.coin_transactions;
create policy coin_self_select on public.coin_transactions for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists claims_self_select on public.daily_claims;
create policy claims_self_select on public.daily_claims for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists requests_insert on public.movie_requests;
create policy requests_insert on public.movie_requests for insert with check (user_id = auth.uid() or user_id is null);
drop policy if exists requests_self_select on public.movie_requests;
create policy requests_self_select on public.movie_requests for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists requests_admin_update on public.movie_requests;
create policy requests_admin_update on public.movie_requests for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists notifications_self_select on public.notifications;
create policy notifications_self_select on public.notifications for select using (user_id = auth.uid());
drop policy if exists notifications_self_update on public.notifications;
create policy notifications_self_update on public.notifications for update using (user_id = auth.uid());

-- Public aggregate views used by the admin dashboard only through admin RLS.
create or replace view public.top_watched_today as
select movie_id, media_type, max(title) as title, max(poster_path) as poster_path,
       count(*) filter (where event_type in ('play','complete')) as watches,
       count(distinct coalesce(user_id::text, session_id)) as unique_viewers
from public.watch_events
where created_at >= current_date
group by movie_id, media_type
order by watches desc;

create or replace view public.rating_summary as
select count(*)::bigint as total_ratings,
       round(avg(rating)::numeric,2) as average_rating,
       count(distinct user_id)::bigint as rating_users
from public.movie_ratings;

-- Secure daily reward. One claim per user per Kenya/server date.
create or replace function public.claim_daily_reward()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  today date := current_date;
  existing_id bigint;
  reward integer := 10;
  new_balance integer;
  streak integer := 1;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  select id into existing_id from public.daily_claims
  where user_id = uid and claim_date = today;

  if existing_id is not null then
    select coins, streak_days into new_balance, streak from public.profiles where id = uid;
    return jsonb_build_object('claimed', false, 'amount', 0, 'coins', coalesce(new_balance,0), 'streak', coalesce(streak,0));
  end if;

  select coalesce(streak_days,0), coalesce(coins,0)
    into streak, new_balance
  from public.profiles where id = uid for update;

  if not exists (
    select 1 from public.daily_claims
    where user_id = uid and claim_date = today - 1
  ) then
    streak := 1;
  else
    streak := greatest(1, streak + 1);
  end if;

  reward := 10 + least(streak, 7) * 2;
  new_balance := new_balance + reward;

  update public.profiles
  set coins = new_balance, streak_days = streak, last_reward_date = today, updated_at = now()
  where id = uid;

  insert into public.daily_claims(user_id, claim_date, amount) values(uid, today, reward);
  insert into public.coin_transactions(user_id, amount, balance_after, type, description)
  values(uid, reward, new_balance, 'daily_reward', 'Daily login reward');

  return jsonb_build_object('claimed', true, 'amount', reward, 'coins', new_balance, 'streak', streak);
end;
$$;

grant execute on function public.claim_daily_reward() to authenticated;

-- Admin aggregate RPC; avoids exposing raw private rows to the browser.
create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  select jsonb_build_object(
    'total_users', (select count(*) from auth.users),
    'users_today', (select count(*) from auth.users where created_at >= current_date),
    'visitors_today', (select count(distinct coalesce(user_id::text, session_id)) from site_visits where created_at >= current_date),
    'visits_today', (select count(*) from site_visits where created_at >= current_date),
    'ratings', (select count(*) from movie_ratings),
    'rating_users', (select count(distinct user_id) from movie_ratings),
    'coins', (select coalesce(sum(coins),0) from profiles),
    'watch_events_today', (select count(*) from watch_events where created_at >= current_date),
    'pending_requests', (select count(*) from movie_requests where status='pending'),
    'total_requests', (select count(*) from movie_requests)
  ) into result;
  return result;
end;
$$;
grant execute on function public.admin_dashboard_stats() to authenticated;

create or replace function public.admin_users(limit_count integer default 100)
returns table(
  id uuid, email text, username text, display_name text, coins integer, xp integer,
  streak_days integer, status text, created_at timestamptz, role text
)
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  return query
  select p.id, u.email, p.username, p.display_name, p.coins, p.xp,
         p.streak_days, p.status, p.created_at, coalesce(r.role,'user')
  from public.profiles p
  join auth.users u on u.id=p.id
  left join public.user_roles r on r.user_id=p.id
  order by p.created_at desc
  limit greatest(1, least(limit_count,500));
end;
$$;
grant execute on function public.admin_users(integer) to authenticated;

create or replace function public.admin_adjust_coins(target_user uuid, amount integer, reason text default 'Admin adjustment')
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare new_balance integer;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  update public.profiles set coins=greatest(0,coins+amount), updated_at=now()
  where id=target_user returning coins into new_balance;
  if new_balance is null then raise exception 'User not found'; end if;
  insert into public.coin_transactions(user_id,amount,balance_after,type,description)
  values(target_user,amount,new_balance,'admin_adjustment',reason);
  return jsonb_build_object('coins',new_balance);
end;
$$;
grant execute on function public.admin_adjust_coins(uuid,integer,text) to authenticated;

create or replace function public.admin_set_user_status(target_user uuid, new_status text)
returns boolean
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if new_status not in ('active','suspended') then raise exception 'Invalid status'; end if;
  update public.profiles set status=new_status, updated_at=now() where id=target_user;
  return found;
end;
$$;
grant execute on function public.admin_set_user_status(uuid,text) to authenticated;

create or replace function public.top_watched_public(limit_count integer default 24)
returns table(movie_id bigint, media_type text, title text, poster_path text, watches bigint, unique_viewers bigint)
language sql stable
security definer set search_path = public
as $$
  select movie_id, media_type, max(title), max(poster_path),
         count(*) filter (where event_type in ('play','complete')),
         count(distinct coalesce(user_id::text, session_id))
  from public.watch_events
  where created_at >= current_date
  group by movie_id, media_type
  order by 5 desc
  limit greatest(1, least(limit_count,50));
$$;
grant execute on function public.top_watched_public(integer) to anon, authenticated;
