-- DECAN MOVIE optional social/reviews upgrade. Run in Supabase SQL editor once.
create table if not exists public.movie_reviews (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete cascade not null, tmdb_id integer not null, media_type text not null default 'movie', title text, body text not null, spoiler boolean not null default false, rating numeric(2,1), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.review_likes (review_id bigint references public.movie_reviews(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(review_id,user_id));
create table if not exists public.user_follows (follower_id uuid references auth.users(id) on delete cascade, following_id uuid references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(follower_id,following_id), check(follower_id<>following_id));
create table if not exists public.user_achievements (id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete cascade not null, achievement_key text not null, unlocked_at timestamptz not null default now(), unique(user_id,achievement_key));
alter table public.movie_reviews enable row level security; alter table public.review_likes enable row level security; alter table public.user_follows enable row level security; alter table public.user_achievements enable row level security;
create policy "reviews readable" on public.movie_reviews for select using (true);
create policy "users create own reviews" on public.movie_reviews for insert with check (auth.uid()=user_id);
create policy "users update own reviews" on public.movie_reviews for update using (auth.uid()=user_id);
create policy "users delete own reviews" on public.movie_reviews for delete using (auth.uid()=user_id);
create policy "review likes readable" on public.review_likes for select using (true);
create policy "users like reviews" on public.review_likes for insert with check (auth.uid()=user_id);
create policy "users unlike reviews" on public.review_likes for delete using (auth.uid()=user_id);
create policy "follows readable" on public.user_follows for select using (true);
create policy "users follow" on public.user_follows for insert with check (auth.uid()=follower_id);
create policy "users unfollow" on public.user_follows for delete using (auth.uid()=follower_id);
create policy "achievements own readable" on public.user_achievements for select using (auth.uid()=user_id);
